version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app:rw
      - ./static/images:/app/static/images:rw
    environment:
      - FLASK_ENV=production
    restart: unless-stopped
